package com.gzsb.root.gzsbroot.dao.mapper;

import com.gzsb.root.gzsbroot.dao.entity.Attendance;
import com.gzsb.root.gzsbroot.dao.entity.AttendanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttendanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_attendance
     *
     * @mbg.generated
     */
    long countByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_attendance
     *
     * @mbg.generated
     */
    int deleteByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_attendance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_attendance
     *
     * @mbg.generated
     */
    int insert(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_attendance
     *
     * @mbg.generated
     */
    int insertSelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_attendance
     *
     * @mbg.generated
     */
    List<Attendance> selectByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_attendance
     *
     * @mbg.generated
     */
    Attendance selectByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_attendance
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Attendance record, @Param("example") AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_attendance
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Attendance record, @Param("example") AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_attendance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_attendance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Attendance record);
}