package com.gzsb.root.gzsbroot.dao.mapper;

import com.gzsb.root.gzsbroot.dao.entity.ConferenceParticipant;
import com.gzsb.root.gzsbroot.dao.entity.ConferenceParticipantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConferenceParticipantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference_participant
     *
     * @mbg.generated
     */
    long countByExample(ConferenceParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference_participant
     *
     * @mbg.generated
     */
    int deleteByExample(ConferenceParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference_participant
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ppId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference_participant
     *
     * @mbg.generated
     */
    int insert(ConferenceParticipant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference_participant
     *
     * @mbg.generated
     */
    int insertSelective(ConferenceParticipant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference_participant
     *
     * @mbg.generated
     */
    List<ConferenceParticipant> selectByExample(ConferenceParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference_participant
     *
     * @mbg.generated
     */
    ConferenceParticipant selectByPrimaryKey(Integer ppId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference_participant
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ConferenceParticipant record, @Param("example") ConferenceParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference_participant
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ConferenceParticipant record, @Param("example") ConferenceParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference_participant
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConferenceParticipant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference_participant
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConferenceParticipant record);
}