package com.gzsb.root.gzsbroot.dao.mapper;

import com.gzsb.root.gzsbroot.dao.entity.Conference;
import com.gzsb.root.gzsbroot.dao.entity.ConferenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConferenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference
     *
     * @mbg.generated
     */
    long countByExample(ConferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference
     *
     * @mbg.generated
     */
    int deleteByExample(ConferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference
     *
     * @mbg.generated
     */
    int insert(Conference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference
     *
     * @mbg.generated
     */
    int insertSelective(Conference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference
     *
     * @mbg.generated
     */
    List<Conference> selectByExample(ConferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference
     *
     * @mbg.generated
     */
    Conference selectByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Conference record, @Param("example") ConferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Conference record, @Param("example") ConferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Conference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_conference
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Conference record);
}