package com.gzsb.root.gzsbroot.dao.mapper;

import com.gzsb.root.gzsbroot.dao.entity.Department;
import com.gzsb.root.gzsbroot.dao.entity.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_department
     *
     * @mbg.generated
     */
    long countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_department
     *
     * @mbg.generated
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_department
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String departmentCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_department
     *
     * @mbg.generated
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_department
     *
     * @mbg.generated
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_department
     *
     * @mbg.generated
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_department
     *
     * @mbg.generated
     */
    Department selectByPrimaryKey(String departmentCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_department
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_department
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Department record);
}