package com.gzsb.root.gzsbroot.dao.mapper;

import com.gzsb.root.gzsbroot.dao.entity.MettingRoom;
import com.gzsb.root.gzsbroot.dao.entity.MettingRoomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MettingRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    long countByExample(MettingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    int deleteByExample(MettingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    int insert(MettingRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    int insertSelective(MettingRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    List<MettingRoom> selectByExample(MettingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    MettingRoom selectByPrimaryKey(Integer mmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MettingRoom record, @Param("example") MettingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MettingRoom record, @Param("example") MettingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MettingRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MettingRoom record);
}