package com.gzsb.root.gzsbroot.dao.mapper;

import com.gzsb.root.gzsbroot.dao.entity.OperatorRole;
import com.gzsb.root.gzsbroot.dao.entity.OperatorRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperatorRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR_ROLE
     *
     * @mbg.generated
     */
    long countByExample(OperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR_ROLE
     *
     * @mbg.generated
     */
    int deleteByExample(OperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR_ROLE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR_ROLE
     *
     * @mbg.generated
     */
    int insert(OperatorRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR_ROLE
     *
     * @mbg.generated
     */
    int insertSelective(OperatorRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR_ROLE
     *
     * @mbg.generated
     */
    List<OperatorRole> selectByExample(OperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR_ROLE
     *
     * @mbg.generated
     */
    OperatorRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR_ROLE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OperatorRole record, @Param("example") OperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR_ROLE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OperatorRole record, @Param("example") OperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR_ROLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OperatorRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR_ROLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OperatorRole record);
}