package com.gzsb.root.gzsbroot.dao.mapper;

import com.gzsb.root.gzsbroot.dao.entity.OperatorPosition;
import com.gzsb.root.gzsbroot.dao.entity.OperatorPositionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperatorPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_operator_position
     *
     * @mbg.generated
     */
    long countByExample(OperatorPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_operator_position
     *
     * @mbg.generated
     */
    int deleteByExample(OperatorPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_operator_position
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer opId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_operator_position
     *
     * @mbg.generated
     */
    int insert(OperatorPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_operator_position
     *
     * @mbg.generated
     */
    int insertSelective(OperatorPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_operator_position
     *
     * @mbg.generated
     */
    List<OperatorPosition> selectByExample(OperatorPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_operator_position
     *
     * @mbg.generated
     */
    OperatorPosition selectByPrimaryKey(Integer opId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_operator_position
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OperatorPosition record, @Param("example") OperatorPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_operator_position
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OperatorPosition record, @Param("example") OperatorPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_operator_position
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OperatorPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_operator_position
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OperatorPosition record);
}