package com.gzsb.root.gzsbroot.dao.mapper;

import com.gzsb.root.gzsbroot.dao.entity.Operator;
import com.gzsb.root.gzsbroot.dao.entity.OperatorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR
     *
     * @mbg.generated
     */
    long countByExample(OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR
     *
     * @mbg.generated
     */
    int deleteByExample(OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String operator);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR
     *
     * @mbg.generated
     */
    int insert(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR
     *
     * @mbg.generated
     */
    int insertSelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR
     *
     * @mbg.generated
     */
    List<Operator> selectByExample(OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR
     *
     * @mbg.generated
     */
    Operator selectByPrimaryKey(String operator);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Operator record, @Param("example") OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Operator record, @Param("example") OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_OPERATOR
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Operator record);
}