package com.gzsb.root.gzsbroot.dao.mapper;

import com.gzsb.root.gzsbroot.dao.entity.Plan;
import com.gzsb.root.gzsbroot.dao.entity.PlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_plan
     *
     * @mbg.generated
     */
    long countByExample(PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_plan
     *
     * @mbg.generated
     */
    int deleteByExample(PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_plan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_plan
     *
     * @mbg.generated
     */
    int insert(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_plan
     *
     * @mbg.generated
     */
    int insertSelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_plan
     *
     * @mbg.generated
     */
    List<Plan> selectByExample(PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_plan
     *
     * @mbg.generated
     */
    Plan selectByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_plan
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Plan record, @Param("example") PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_plan
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Plan record, @Param("example") PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Plan record);
}