package com.gzsb.root.gzsbroot.dao.mapper;

import com.gzsb.root.gzsbroot.dao.entity.Process;
import com.gzsb.root.gzsbroot.dao.entity.ProcessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_process
     *
     * @mbg.generated
     */
    long countByExample(ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_process
     *
     * @mbg.generated
     */
    int deleteByExample(ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_process
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer processId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_process
     *
     * @mbg.generated
     */
    int insert(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_process
     *
     * @mbg.generated
     */
    int insertSelective(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_process
     *
     * @mbg.generated
     */
    List<Process> selectByExample(ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_process
     *
     * @mbg.generated
     */
    Process selectByPrimaryKey(Integer processId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_process
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Process record, @Param("example") ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_process
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Process record, @Param("example") ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_process
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_process
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Process record);
}