package com.gzsb.root.gzsbroot.dao.mapper;

import com.gzsb.root.gzsbroot.dao.entity.Role;
import com.gzsb.root.gzsbroot.dao.entity.RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_ROLE
     *
     * @mbg.generated
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_ROLE
     *
     * @mbg.generated
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_ROLE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String roleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_ROLE
     *
     * @mbg.generated
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_ROLE
     *
     * @mbg.generated
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_ROLE
     *
     * @mbg.generated
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_ROLE
     *
     * @mbg.generated
     */
    Role selectByPrimaryKey(String roleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_ROLE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_ROLE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_ROLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GZSB_ROLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Role record);
}