package com.gzsb.root.gzsbroot.dao.mapper;

import com.gzsb.root.gzsbroot.dao.entity.Status;
import com.gzsb.root.gzsbroot.dao.entity.StatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_status
     *
     * @mbg.generated
     */
    long countByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_status
     *
     * @mbg.generated
     */
    int deleteByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_status
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String planStatusCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_status
     *
     * @mbg.generated
     */
    int insert(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_status
     *
     * @mbg.generated
     */
    int insertSelective(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_status
     *
     * @mbg.generated
     */
    List<Status> selectByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_status
     *
     * @mbg.generated
     */
    Status selectByPrimaryKey(String planStatusCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_status
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Status record, @Param("example") StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_status
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Status record, @Param("example") StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Status record);
}