spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
    timeout: 1000
  application:
    name: GZSB-OA
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/gzsbdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  thymeleaf:
    cache: true
#  activiti:
#    check-process-definitions: false
server:
  port: 8080


logging:
  level:
    com.gzsb.root.gzsbroot.dao: debug
