package com.gzsb.root.gzsbroot.dao.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class Attendance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_attendance.A_ID
     *
     * @mbg.generated
     */
    private Integer aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_attendance.TYPE_CODE
     *
     * @mbg.generated
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_attendance.PLAN_STATUS_CODE
     *
     * @mbg.generated
     */
    private String planStatusCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_attendance.OPERATOR
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_attendance.ID_ADDRESS
     *
     * @mbg.generated
     */
    private String idAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_attendance.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_attendance.A_TIME
     *
     * @mbg.generated
     */
    private Date aTime;

    private String departmentName;

    private String departmentCode;

    private String statusDescription;

    private String typeDescription;

    private Integer pageIndex;

    private Integer limit;

    private boolean seven;

    private boolean oneMonth;
}
