package com.gzsb.root.gzsbroot.dao.entity;

import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class Bulletin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_bulletin.BULLETIN_ID
     *
     * @mbg.generated
     */
    private Integer bulletinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_bulletin.OPERATOR
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_bulletin.PLAN_STATUS_CODE
     *
     * @mbg.generated
     */
    private String planStatusCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_bulletin.DEPARTMENT_CODE
     *
     * @mbg.generated
     */
    private String departmentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_bulletin.TYPE_CODE
     *
     * @mbg.generated
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_bulletin.THEME
     *
     * @mbg.generated
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_bulletin.BULLETIN_CONTENT
     *
     * @mbg.generated
     */
    private String bulletinContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_bulletin.TIME
     *
     * @mbg.generated
     */
    private Date time;

    private Status status;

    private Department department;

    private Type type;

    @Override
    public String toString() {
        return "bulletin{" +
                "bulletinId=" + bulletinId +
                ", operator='" + operator + '\'' +
                ", planStatusCode='" + planStatusCode + '\'' +
                ", departmentCode='" + departmentCode + '\'' +
                ", typeCode='" + typeCode + '\'' +
                ", theme='" + theme + '\'' +
                ", bulletinContent='" + bulletinContent + '\'' +
                ", time=" + time +
                ", status=" + status +
                ", department=" + department +
                ", type=" + type +
                '}';
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public Type getType() {
        return type;
    }

    public void setType(Type type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_bulletin.BULLETIN_ID
     *
     * @return the value of gzsb_bulletin.BULLETIN_ID
     *
     * @mbg.generated
     */
    public Integer getBulletinId() {
        return bulletinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_bulletin.BULLETIN_ID
     *
     * @param bulletinId the value for gzsb_bulletin.BULLETIN_ID
     *
     * @mbg.generated
     */
    public void setBulletinId(Integer bulletinId) {
        this.bulletinId = bulletinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_bulletin.OPERATOR
     *
     * @return the value of gzsb_bulletin.OPERATOR
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_bulletin.OPERATOR
     *
     * @param operator the value for gzsb_bulletin.OPERATOR
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_bulletin.PLAN_STATUS_CODE
     *
     * @return the value of gzsb_bulletin.PLAN_STATUS_CODE
     *
     * @mbg.generated
     */
    public String getPlanStatusCode() {
        return planStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_bulletin.PLAN_STATUS_CODE
     *
     * @param planStatusCode the value for gzsb_bulletin.PLAN_STATUS_CODE
     *
     * @mbg.generated
     */
    public void setPlanStatusCode(String planStatusCode) {
        this.planStatusCode = planStatusCode == null ? null : planStatusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_bulletin.DEPARTMENT_CODE
     *
     * @return the value of gzsb_bulletin.DEPARTMENT_CODE
     *
     * @mbg.generated
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_bulletin.DEPARTMENT_CODE
     *
     * @param departmentCode the value for gzsb_bulletin.DEPARTMENT_CODE
     *
     * @mbg.generated
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_bulletin.TYPE_CODE
     *
     * @return the value of gzsb_bulletin.TYPE_CODE
     *
     * @mbg.generated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_bulletin.TYPE_CODE
     *
     * @param typeCode the value for gzsb_bulletin.TYPE_CODE
     *
     * @mbg.generated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_bulletin.THEME
     *
     * @return the value of gzsb_bulletin.THEME
     *
     * @mbg.generated
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_bulletin.THEME
     *
     * @param theme the value for gzsb_bulletin.THEME
     *
     * @mbg.generated
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_bulletin.BULLETIN_CONTENT
     *
     * @return the value of gzsb_bulletin.BULLETIN_CONTENT
     *
     * @mbg.generated
     */
    public String getBulletinContent() {
        return bulletinContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_bulletin.BULLETIN_CONTENT
     *
     * @param bulletinContent the value for gzsb_bulletin.BULLETIN_CONTENT
     *
     * @mbg.generated
     */
    public void setBulletinContent(String bulletinContent) {
        this.bulletinContent = bulletinContent == null ? null : bulletinContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_bulletin.TIME
     *
     * @return the value of gzsb_bulletin.TIME
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_bulletin.TIME
     *
     * @param time the value for gzsb_bulletin.TIME
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}