package com.gzsb.root.gzsbroot.dao.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BulletinExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    public BulletinExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBulletinIdIsNull() {
            addCriterion("BULLETIN_ID is null");
            return (Criteria) this;
        }

        public Criteria andBulletinIdIsNotNull() {
            addCriterion("BULLETIN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBulletinIdEqualTo(Integer value) {
            addCriterion("BULLETIN_ID =", value, "bulletinId");
            return (Criteria) this;
        }

        public Criteria andBulletinIdNotEqualTo(Integer value) {
            addCriterion("BULLETIN_ID <>", value, "bulletinId");
            return (Criteria) this;
        }

        public Criteria andBulletinIdGreaterThan(Integer value) {
            addCriterion("BULLETIN_ID >", value, "bulletinId");
            return (Criteria) this;
        }

        public Criteria andBulletinIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("BULLETIN_ID >=", value, "bulletinId");
            return (Criteria) this;
        }

        public Criteria andBulletinIdLessThan(Integer value) {
            addCriterion("BULLETIN_ID <", value, "bulletinId");
            return (Criteria) this;
        }

        public Criteria andBulletinIdLessThanOrEqualTo(Integer value) {
            addCriterion("BULLETIN_ID <=", value, "bulletinId");
            return (Criteria) this;
        }

        public Criteria andBulletinIdIn(List<Integer> values) {
            addCriterion("BULLETIN_ID in", values, "bulletinId");
            return (Criteria) this;
        }

        public Criteria andBulletinIdNotIn(List<Integer> values) {
            addCriterion("BULLETIN_ID not in", values, "bulletinId");
            return (Criteria) this;
        }

        public Criteria andBulletinIdBetween(Integer value1, Integer value2) {
            addCriterion("BULLETIN_ID between", value1, value2, "bulletinId");
            return (Criteria) this;
        }

        public Criteria andBulletinIdNotBetween(Integer value1, Integer value2) {
            addCriterion("BULLETIN_ID not between", value1, value2, "bulletinId");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("OPERATOR is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("OPERATOR is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("OPERATOR =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("OPERATOR <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("OPERATOR >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATOR >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("OPERATOR <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("OPERATOR <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("OPERATOR like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("OPERATOR not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("OPERATOR in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("OPERATOR not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("OPERATOR between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("OPERATOR not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andPlanStatusCodeIsNull() {
            addCriterion("PLAN_STATUS_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPlanStatusCodeIsNotNull() {
            addCriterion("PLAN_STATUS_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPlanStatusCodeEqualTo(String value) {
            addCriterion("PLAN_STATUS_CODE =", value, "planStatusCode");
            return (Criteria) this;
        }

        public Criteria andPlanStatusCodeNotEqualTo(String value) {
            addCriterion("PLAN_STATUS_CODE <>", value, "planStatusCode");
            return (Criteria) this;
        }

        public Criteria andPlanStatusCodeGreaterThan(String value) {
            addCriterion("PLAN_STATUS_CODE >", value, "planStatusCode");
            return (Criteria) this;
        }

        public Criteria andPlanStatusCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PLAN_STATUS_CODE >=", value, "planStatusCode");
            return (Criteria) this;
        }

        public Criteria andPlanStatusCodeLessThan(String value) {
            addCriterion("PLAN_STATUS_CODE <", value, "planStatusCode");
            return (Criteria) this;
        }

        public Criteria andPlanStatusCodeLessThanOrEqualTo(String value) {
            addCriterion("PLAN_STATUS_CODE <=", value, "planStatusCode");
            return (Criteria) this;
        }

        public Criteria andPlanStatusCodeLike(String value) {
            addCriterion("PLAN_STATUS_CODE like", value, "planStatusCode");
            return (Criteria) this;
        }

        public Criteria andPlanStatusCodeNotLike(String value) {
            addCriterion("PLAN_STATUS_CODE not like", value, "planStatusCode");
            return (Criteria) this;
        }

        public Criteria andPlanStatusCodeIn(List<String> values) {
            addCriterion("PLAN_STATUS_CODE in", values, "planStatusCode");
            return (Criteria) this;
        }

        public Criteria andPlanStatusCodeNotIn(List<String> values) {
            addCriterion("PLAN_STATUS_CODE not in", values, "planStatusCode");
            return (Criteria) this;
        }

        public Criteria andPlanStatusCodeBetween(String value1, String value2) {
            addCriterion("PLAN_STATUS_CODE between", value1, value2, "planStatusCode");
            return (Criteria) this;
        }

        public Criteria andPlanStatusCodeNotBetween(String value1, String value2) {
            addCriterion("PLAN_STATUS_CODE not between", value1, value2, "planStatusCode");
            return (Criteria) this;
        }

        public Criteria andDepartmentCodeIsNull() {
            addCriterion("DEPARTMENT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentCodeIsNotNull() {
            addCriterion("DEPARTMENT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentCodeEqualTo(String value) {
            addCriterion("DEPARTMENT_CODE =", value, "departmentCode");
            return (Criteria) this;
        }

        public Criteria andDepartmentCodeNotEqualTo(String value) {
            addCriterion("DEPARTMENT_CODE <>", value, "departmentCode");
            return (Criteria) this;
        }

        public Criteria andDepartmentCodeGreaterThan(String value) {
            addCriterion("DEPARTMENT_CODE >", value, "departmentCode");
            return (Criteria) this;
        }

        public Criteria andDepartmentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("DEPARTMENT_CODE >=", value, "departmentCode");
            return (Criteria) this;
        }

        public Criteria andDepartmentCodeLessThan(String value) {
            addCriterion("DEPARTMENT_CODE <", value, "departmentCode");
            return (Criteria) this;
        }

        public Criteria andDepartmentCodeLessThanOrEqualTo(String value) {
            addCriterion("DEPARTMENT_CODE <=", value, "departmentCode");
            return (Criteria) this;
        }

        public Criteria andDepartmentCodeLike(String value) {
            addCriterion("DEPARTMENT_CODE like", value, "departmentCode");
            return (Criteria) this;
        }

        public Criteria andDepartmentCodeNotLike(String value) {
            addCriterion("DEPARTMENT_CODE not like", value, "departmentCode");
            return (Criteria) this;
        }

        public Criteria andDepartmentCodeIn(List<String> values) {
            addCriterion("DEPARTMENT_CODE in", values, "departmentCode");
            return (Criteria) this;
        }

        public Criteria andDepartmentCodeNotIn(List<String> values) {
            addCriterion("DEPARTMENT_CODE not in", values, "departmentCode");
            return (Criteria) this;
        }

        public Criteria andDepartmentCodeBetween(String value1, String value2) {
            addCriterion("DEPARTMENT_CODE between", value1, value2, "departmentCode");
            return (Criteria) this;
        }

        public Criteria andDepartmentCodeNotBetween(String value1, String value2) {
            addCriterion("DEPARTMENT_CODE not between", value1, value2, "departmentCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeIsNull() {
            addCriterion("TYPE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTypeCodeIsNotNull() {
            addCriterion("TYPE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeCodeEqualTo(String value) {
            addCriterion("TYPE_CODE =", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeNotEqualTo(String value) {
            addCriterion("TYPE_CODE <>", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeGreaterThan(String value) {
            addCriterion("TYPE_CODE >", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE_CODE >=", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeLessThan(String value) {
            addCriterion("TYPE_CODE <", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("TYPE_CODE <=", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeLike(String value) {
            addCriterion("TYPE_CODE like", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeNotLike(String value) {
            addCriterion("TYPE_CODE not like", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeIn(List<String> values) {
            addCriterion("TYPE_CODE in", values, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeNotIn(List<String> values) {
            addCriterion("TYPE_CODE not in", values, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeBetween(String value1, String value2) {
            addCriterion("TYPE_CODE between", value1, value2, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeNotBetween(String value1, String value2) {
            addCriterion("TYPE_CODE not between", value1, value2, "typeCode");
            return (Criteria) this;
        }

        public Criteria andThemeIsNull() {
            addCriterion("THEME is null");
            return (Criteria) this;
        }

        public Criteria andThemeIsNotNull() {
            addCriterion("THEME is not null");
            return (Criteria) this;
        }

        public Criteria andThemeEqualTo(String value) {
            addCriterion("THEME =", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeNotEqualTo(String value) {
            addCriterion("THEME <>", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeGreaterThan(String value) {
            addCriterion("THEME >", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeGreaterThanOrEqualTo(String value) {
            addCriterion("THEME >=", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeLessThan(String value) {
            addCriterion("THEME <", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeLessThanOrEqualTo(String value) {
            addCriterion("THEME <=", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeLike(String value) {
            addCriterion("THEME like", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeNotLike(String value) {
            addCriterion("THEME not like", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeIn(List<String> values) {
            addCriterion("THEME in", values, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeNotIn(List<String> values) {
            addCriterion("THEME not in", values, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeBetween(String value1, String value2) {
            addCriterion("THEME between", value1, value2, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeNotBetween(String value1, String value2) {
            addCriterion("THEME not between", value1, value2, "theme");
            return (Criteria) this;
        }

        public Criteria andBulletinContentIsNull() {
            addCriterion("BULLETIN_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andBulletinContentIsNotNull() {
            addCriterion("BULLETIN_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andBulletinContentEqualTo(String value) {
            addCriterion("BULLETIN_CONTENT =", value, "bulletinContent");
            return (Criteria) this;
        }

        public Criteria andBulletinContentNotEqualTo(String value) {
            addCriterion("BULLETIN_CONTENT <>", value, "bulletinContent");
            return (Criteria) this;
        }

        public Criteria andBulletinContentGreaterThan(String value) {
            addCriterion("BULLETIN_CONTENT >", value, "bulletinContent");
            return (Criteria) this;
        }

        public Criteria andBulletinContentGreaterThanOrEqualTo(String value) {
            addCriterion("BULLETIN_CONTENT >=", value, "bulletinContent");
            return (Criteria) this;
        }

        public Criteria andBulletinContentLessThan(String value) {
            addCriterion("BULLETIN_CONTENT <", value, "bulletinContent");
            return (Criteria) this;
        }

        public Criteria andBulletinContentLessThanOrEqualTo(String value) {
            addCriterion("BULLETIN_CONTENT <=", value, "bulletinContent");
            return (Criteria) this;
        }

        public Criteria andBulletinContentLike(String value) {
            addCriterion("BULLETIN_CONTENT like", value, "bulletinContent");
            return (Criteria) this;
        }

        public Criteria andBulletinContentNotLike(String value) {
            addCriterion("BULLETIN_CONTENT not like", value, "bulletinContent");
            return (Criteria) this;
        }

        public Criteria andBulletinContentIn(List<String> values) {
            addCriterion("BULLETIN_CONTENT in", values, "bulletinContent");
            return (Criteria) this;
        }

        public Criteria andBulletinContentNotIn(List<String> values) {
            addCriterion("BULLETIN_CONTENT not in", values, "bulletinContent");
            return (Criteria) this;
        }

        public Criteria andBulletinContentBetween(String value1, String value2) {
            addCriterion("BULLETIN_CONTENT between", value1, value2, "bulletinContent");
            return (Criteria) this;
        }

        public Criteria andBulletinContentNotBetween(String value1, String value2) {
            addCriterion("BULLETIN_CONTENT not between", value1, value2, "bulletinContent");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("TIME is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("TIME =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("TIME <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("TIME >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("TIME >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("TIME <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("TIME <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("TIME in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("TIME not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("TIME between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("TIME not between", value1, value2, "time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gzsb_bulletin
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}