package com.gzsb.root.gzsbroot.dao.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

@Data
public class Conference  {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_conference.C_ID
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_conference.TYPE_CODE
     *
     * @mbg.generated
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_conference.DEPARTMENT_CODE
     *
     * @mbg.generated
     */
    private String departmentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_conference.GZS_OPERATOR
     *
     * @mbg.generated
     */
    private String gzsOperator;

    private Type type;

    private Department department;

    private MettingRoom mettingRoom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_conference.MM_ID
     *
     * @mbg.generated
     */
    private Integer mmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_conference.THEME
     *
     * @mbg.generated
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_conference.START_TIME
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd hh:mm", timezone = "GMT+8")
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_conference.END_TIME
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd hh:mm", timezone = "GMT+8")
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_conference.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_conference.OPERATOR
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_conference.CONFERENCE_FILE
     *
     * @mbg.generated
     */
    private String conferenceFile;

    private int status;

    private List<String> realName;
}