package com.gzsb.root.gzsbroot.dao.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

@Data
public class Department  {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_department.DEPARTMENT_CODE
     *
     * @mbg.generated
     */
    private String departmentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_department.FATHER_CODE
     *
     * @mbg.generated
     */
    private String fatherCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_department.DEPARTMENT_NAME
     *
     * @mbg.generated
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_department.WORK_TIME_AM
     *
     * @mbg.generated
     */
//    @DateTimeFormat(pattern = "hh:mm")
    @JsonFormat(pattern = "HH:mm",timezone = "GMT+8")
    private Date workTimeAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_department.WORK_TIME_PM
     *
     * @mbg.generated
     */
//    @DateTimeFormat(pattern = "hh:mm")
    @JsonFormat(pattern = "HH:mm",timezone = "GMT+8")
    private Date workTimePm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_department.SORT
     *
     * @mbg.generated
     */
    private Integer sort;

    private String fatherName;

    public String getFatherName() {
        return fatherName;
    }

    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }


}