package com.gzsb.root.gzsbroot.dao.entity;

import java.io.Serializable;

public class DepartmentPosition   {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_department_position.POSITION_ID
     *
     * @mbg.generated
     */
    private Integer positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_department_position.DEPARTMENT_CODE
     *
     * @mbg.generated
     */
    private String departmentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_department_position.POSITION_NAME
     *
     * @mbg.generated
     */
    private String positionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_department_position.SORT
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_department_position.POSITION_ID
     *
     * @return the value of gzsb_department_position.POSITION_ID
     *
     * @mbg.generated
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_department_position.POSITION_ID
     *
     * @param positionId the value for gzsb_department_position.POSITION_ID
     *
     * @mbg.generated
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_department_position.DEPARTMENT_CODE
     *
     * @return the value of gzsb_department_position.DEPARTMENT_CODE
     *
     * @mbg.generated
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_department_position.DEPARTMENT_CODE
     *
     * @param departmentCode the value for gzsb_department_position.DEPARTMENT_CODE
     *
     * @mbg.generated
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_department_position.POSITION_NAME
     *
     * @return the value of gzsb_department_position.POSITION_NAME
     *
     * @mbg.generated
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_department_position.POSITION_NAME
     *
     * @param positionName the value for gzsb_department_position.POSITION_NAME
     *
     * @mbg.generated
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_department_position.SORT
     *
     * @return the value of gzsb_department_position.SORT
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_department_position.SORT
     *
     * @param sort the value for gzsb_department_position.SORT
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}