package com.gzsb.root.gzsbroot.dao.entity;

import lombok.Data;

import java.io.Serializable;
@Data
public class MettingRoom implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_metting_room.MM_ID
     *
     * @mbg.generated
     */
    private Integer mmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_metting_room.METTING_ROOM_NAME
     *
     * @mbg.generated
     */
    private String mettingRoomName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_metting_room.METTING_ADDRESS
     *
     * @mbg.generated
     */
    private String mettingAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_metting_room.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    private Boolean status;



}