package com.gzsb.root.gzsbroot.dao.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class MettingRoomExample   {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    public MettingRoomExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMmIdIsNull() {
            addCriterion("MM_ID is null");
            return (Criteria) this;
        }

        public Criteria andMmIdIsNotNull() {
            addCriterion("MM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMmIdEqualTo(Integer value) {
            addCriterion("MM_ID =", value, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdNotEqualTo(Integer value) {
            addCriterion("MM_ID <>", value, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdGreaterThan(Integer value) {
            addCriterion("MM_ID >", value, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("MM_ID >=", value, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdLessThan(Integer value) {
            addCriterion("MM_ID <", value, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdLessThanOrEqualTo(Integer value) {
            addCriterion("MM_ID <=", value, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdIn(List<Integer> values) {
            addCriterion("MM_ID in", values, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdNotIn(List<Integer> values) {
            addCriterion("MM_ID not in", values, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdBetween(Integer value1, Integer value2) {
            addCriterion("MM_ID between", value1, value2, "mmId");
            return (Criteria) this;
        }

        public Criteria andMmIdNotBetween(Integer value1, Integer value2) {
            addCriterion("MM_ID not between", value1, value2, "mmId");
            return (Criteria) this;
        }

        public Criteria andMettingRoomNameIsNull() {
            addCriterion("METTING_ROOM_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMettingRoomNameIsNotNull() {
            addCriterion("METTING_ROOM_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMettingRoomNameEqualTo(String value) {
            addCriterion("METTING_ROOM_NAME =", value, "mettingRoomName");
            return (Criteria) this;
        }

        public Criteria andMettingRoomNameNotEqualTo(String value) {
            addCriterion("METTING_ROOM_NAME <>", value, "mettingRoomName");
            return (Criteria) this;
        }

        public Criteria andMettingRoomNameGreaterThan(String value) {
            addCriterion("METTING_ROOM_NAME >", value, "mettingRoomName");
            return (Criteria) this;
        }

        public Criteria andMettingRoomNameGreaterThanOrEqualTo(String value) {
            addCriterion("METTING_ROOM_NAME >=", value, "mettingRoomName");
            return (Criteria) this;
        }

        public Criteria andMettingRoomNameLessThan(String value) {
            addCriterion("METTING_ROOM_NAME <", value, "mettingRoomName");
            return (Criteria) this;
        }

        public Criteria andMettingRoomNameLessThanOrEqualTo(String value) {
            addCriterion("METTING_ROOM_NAME <=", value, "mettingRoomName");
            return (Criteria) this;
        }

        public Criteria andMettingRoomNameLike(String value) {
            addCriterion("METTING_ROOM_NAME like", value, "mettingRoomName");
            return (Criteria) this;
        }

        public Criteria andMettingRoomNameNotLike(String value) {
            addCriterion("METTING_ROOM_NAME not like", value, "mettingRoomName");
            return (Criteria) this;
        }

        public Criteria andMettingRoomNameIn(List<String> values) {
            addCriterion("METTING_ROOM_NAME in", values, "mettingRoomName");
            return (Criteria) this;
        }

        public Criteria andMettingRoomNameNotIn(List<String> values) {
            addCriterion("METTING_ROOM_NAME not in", values, "mettingRoomName");
            return (Criteria) this;
        }

        public Criteria andMettingRoomNameBetween(String value1, String value2) {
            addCriterion("METTING_ROOM_NAME between", value1, value2, "mettingRoomName");
            return (Criteria) this;
        }

        public Criteria andMettingRoomNameNotBetween(String value1, String value2) {
            addCriterion("METTING_ROOM_NAME not between", value1, value2, "mettingRoomName");
            return (Criteria) this;
        }

        public Criteria andMettingAddressIsNull() {
            addCriterion("METTING_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andMettingAddressIsNotNull() {
            addCriterion("METTING_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andMettingAddressEqualTo(String value) {
            addCriterion("METTING_ADDRESS =", value, "mettingAddress");
            return (Criteria) this;
        }

        public Criteria andMettingAddressNotEqualTo(String value) {
            addCriterion("METTING_ADDRESS <>", value, "mettingAddress");
            return (Criteria) this;
        }

        public Criteria andMettingAddressGreaterThan(String value) {
            addCriterion("METTING_ADDRESS >", value, "mettingAddress");
            return (Criteria) this;
        }

        public Criteria andMettingAddressGreaterThanOrEqualTo(String value) {
            addCriterion("METTING_ADDRESS >=", value, "mettingAddress");
            return (Criteria) this;
        }

        public Criteria andMettingAddressLessThan(String value) {
            addCriterion("METTING_ADDRESS <", value, "mettingAddress");
            return (Criteria) this;
        }

        public Criteria andMettingAddressLessThanOrEqualTo(String value) {
            addCriterion("METTING_ADDRESS <=", value, "mettingAddress");
            return (Criteria) this;
        }

        public Criteria andMettingAddressLike(String value) {
            addCriterion("METTING_ADDRESS like", value, "mettingAddress");
            return (Criteria) this;
        }

        public Criteria andMettingAddressNotLike(String value) {
            addCriterion("METTING_ADDRESS not like", value, "mettingAddress");
            return (Criteria) this;
        }

        public Criteria andMettingAddressIn(List<String> values) {
            addCriterion("METTING_ADDRESS in", values, "mettingAddress");
            return (Criteria) this;
        }

        public Criteria andMettingAddressNotIn(List<String> values) {
            addCriterion("METTING_ADDRESS not in", values, "mettingAddress");
            return (Criteria) this;
        }

        public Criteria andMettingAddressBetween(String value1, String value2) {
            addCriterion("METTING_ADDRESS between", value1, value2, "mettingAddress");
            return (Criteria) this;
        }

        public Criteria andMettingAddressNotBetween(String value1, String value2) {
            addCriterion("METTING_ADDRESS not between", value1, value2, "mettingAddress");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gzsb_metting_room
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}