package com.gzsb.root.gzsbroot.dao.entity;

import java.io.Serializable;

public class OperatorPosition   {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_operator_position.OP_ID
     *
     * @mbg.generated
     */
    private Integer opId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_operator_position.POSITION_ID
     *
     * @mbg.generated
     */
    private Integer positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_operator_position.OPERATOR
     *
     * @mbg.generated
     */
    private String operator;

    private String departmentName;
    private String positionName;
    private String departmentCode;

    @Override
    public String toString() {
        return "OperatorPosition{" +
                "opId=" + opId +
                ", positionId=" + positionId +
                ", operator='" + operator + '\'' +
                ", departmentName='" + departmentName + '\'' +
                ", positionName='" + positionName + '\'' +
                ", departmentCode='" + departmentCode + '\'' +
                '}';
    }

    public String getPositionName() {
        return positionName;
    }

    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    public String getDepartmentCode() {
        return departmentCode;
    }

    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode;
    }

    public String getDepartmentName() {
        return departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_operator_position.OP_ID
     *
     * @return the value of gzsb_operator_position.OP_ID
     *
     * @mbg.generated
     */
    public Integer getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_operator_position.OP_ID
     *
     * @param opId the value for gzsb_operator_position.OP_ID
     *
     * @mbg.generated
     */
    public void setOpId(Integer opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_operator_position.POSITION_ID
     *
     * @return the value of gzsb_operator_position.POSITION_ID
     *
     * @mbg.generated
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_operator_position.POSITION_ID
     *
     * @param positionId the value for gzsb_operator_position.POSITION_ID
     *
     * @mbg.generated
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_operator_position.OPERATOR
     *
     * @return the value of gzsb_operator_position.OPERATOR
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_operator_position.OPERATOR
     *
     * @param operator the value for gzsb_operator_position.OPERATOR
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }
}