package com.gzsb.root.gzsbroot.dao.entity;

import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

@Data
public class Operator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_OPERATOR.OPERATOR
     *
     * @mbg.generated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_OPERATOR.PLAN_STATUS_CODE
     *
     * @mbg.generated
     */
    private String planStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_OPERATOR.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_OPERATOR.PASSWORD_SALT
     *
     * @mbg.generated
     */
    private String passwordSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_OPERATOR.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_OPERATOR.REAL_NAME
     *
     * @mbg.generated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_OPERATOR.JOB_NUM
     *
     * @mbg.generated
     */
    private String jobNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_OPERATOR.PHONE
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_OPERATOR.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    private String departmentName;

    private String positionName;

    private Integer positionId;

    private List<String> roleCodes;

    private String departmentCode;

    private List<Role> role;
}