package com.gzsb.root.gzsbroot.dao.entity;

import java.io.Serializable;

public class OperatorRole   {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_OPERATOR_ROLE.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_OPERATOR_ROLE.OPERATOR
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_OPERATOR_ROLE.ROLE_CODE
     *
     * @mbg.generated
     */
    private String roleCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GZSB_OPERATOR_ROLE.ID
     *
     * @return the value of GZSB_OPERATOR_ROLE.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GZSB_OPERATOR_ROLE.ID
     *
     * @param id the value for GZSB_OPERATOR_ROLE.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GZSB_OPERATOR_ROLE.OPERATOR
     *
     * @return the value of GZSB_OPERATOR_ROLE.OPERATOR
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GZSB_OPERATOR_ROLE.OPERATOR
     *
     * @param operator the value for GZSB_OPERATOR_ROLE.OPERATOR
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GZSB_OPERATOR_ROLE.ROLE_CODE
     *
     * @return the value of GZSB_OPERATOR_ROLE.ROLE_CODE
     *
     * @mbg.generated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GZSB_OPERATOR_ROLE.ROLE_CODE
     *
     * @param roleCode the value for GZSB_OPERATOR_ROLE.ROLE_CODE
     *
     * @mbg.generated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }
}