package com.gzsb.root.gzsbroot.dao.entity;

import java.io.Serializable;

public class Permission   {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_PERMISSION.PERMISSION_CODE
     *
     * @mbg.generated
     */
    private String permissionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_PERMISSION.PERMISSION_NAME
     *
     * @mbg.generated
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_PERMISSION.PERMISSION_URL
     *
     * @mbg.generated
     */
    private String permissionUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_PERMISSION.FATHER_CODE
     *
     * @mbg.generated
     */
    private String fatherCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_PERMISSION.SORT
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GZSB_PERMISSION.PERMISSION_CODE
     *
     * @return the value of GZSB_PERMISSION.PERMISSION_CODE
     *
     * @mbg.generated
     */
    public String getPermissionCode() {
        return permissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GZSB_PERMISSION.PERMISSION_CODE
     *
     * @param permissionCode the value for GZSB_PERMISSION.PERMISSION_CODE
     *
     * @mbg.generated
     */
    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode == null ? null : permissionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GZSB_PERMISSION.PERMISSION_NAME
     *
     * @return the value of GZSB_PERMISSION.PERMISSION_NAME
     *
     * @mbg.generated
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GZSB_PERMISSION.PERMISSION_NAME
     *
     * @param permissionName the value for GZSB_PERMISSION.PERMISSION_NAME
     *
     * @mbg.generated
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GZSB_PERMISSION.PERMISSION_URL
     *
     * @return the value of GZSB_PERMISSION.PERMISSION_URL
     *
     * @mbg.generated
     */
    public String getPermissionUrl() {
        return permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GZSB_PERMISSION.PERMISSION_URL
     *
     * @param permissionUrl the value for GZSB_PERMISSION.PERMISSION_URL
     *
     * @mbg.generated
     */
    public void setPermissionUrl(String permissionUrl) {
        this.permissionUrl = permissionUrl == null ? null : permissionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GZSB_PERMISSION.FATHER_CODE
     *
     * @return the value of GZSB_PERMISSION.FATHER_CODE
     *
     * @mbg.generated
     */
    public String getFatherCode() {
        return fatherCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GZSB_PERMISSION.FATHER_CODE
     *
     * @param fatherCode the value for GZSB_PERMISSION.FATHER_CODE
     *
     * @mbg.generated
     */
    public void setFatherCode(String fatherCode) {
        this.fatherCode = fatherCode == null ? null : fatherCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GZSB_PERMISSION.SORT
     *
     * @return the value of GZSB_PERMISSION.SORT
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GZSB_PERMISSION.SORT
     *
     * @param sort the value for GZSB_PERMISSION.SORT
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}