package com.gzsb.root.gzsbroot.dao.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

@Data
public class Plan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_plan.PLAN_ID
     *
     * @mbg.generated
     */
    private Integer planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_plan.DEPARTMENT_CODE
     *
     * @mbg.generated
     */
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_plan.OPERATOR
     *
     * @mbg.generated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_plan.PLAN_STATUS_CODE
     *
     * @mbg.generated
     */
    private String planStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_plan.TYPE_CODE
     *
     * @mbg.generated
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_plan.PLAN_CONTENT
     *
     * @mbg.generated
     */
    private String planContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_plan.PLAN_TIME
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date planTime;


    private String departmentName;

    private String statusDescription;

    private String typeDescription;

    private int delayDays;

    private int overtimeDays;

}
