package com.gzsb.root.gzsbroot.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Process   {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_process.PROCESS_ID
     *
     * @mbg.generated
     */
    private Integer processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_process.TYPE_CODE
     *
     * @mbg.generated
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_process.PLAN_STATUS_CODE
     *
     * @mbg.generated
     */
    private String planStatusCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_process.THEME
     *
     * @mbg.generated
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_process.PROCESS_TYPE
     *
     * @mbg.generated
     */
    private String processType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_process.APPLY_TIME
     *
     * @mbg.generated
     */
    private Date applyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_process.PROCESS_ID
     *
     * @return the value of gzsb_process.PROCESS_ID
     *
     * @mbg.generated
     */
    public Integer getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_process.PROCESS_ID
     *
     * @param processId the value for gzsb_process.PROCESS_ID
     *
     * @mbg.generated
     */
    public void setProcessId(Integer processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_process.TYPE_CODE
     *
     * @return the value of gzsb_process.TYPE_CODE
     *
     * @mbg.generated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_process.TYPE_CODE
     *
     * @param typeCode the value for gzsb_process.TYPE_CODE
     *
     * @mbg.generated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_process.PLAN_STATUS_CODE
     *
     * @return the value of gzsb_process.PLAN_STATUS_CODE
     *
     * @mbg.generated
     */
    public String getPlanStatusCode() {
        return planStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_process.PLAN_STATUS_CODE
     *
     * @param planStatusCode the value for gzsb_process.PLAN_STATUS_CODE
     *
     * @mbg.generated
     */
    public void setPlanStatusCode(String planStatusCode) {
        this.planStatusCode = planStatusCode == null ? null : planStatusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_process.THEME
     *
     * @return the value of gzsb_process.THEME
     *
     * @mbg.generated
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_process.THEME
     *
     * @param theme the value for gzsb_process.THEME
     *
     * @mbg.generated
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_process.PROCESS_TYPE
     *
     * @return the value of gzsb_process.PROCESS_TYPE
     *
     * @mbg.generated
     */
    public String getProcessType() {
        return processType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_process.PROCESS_TYPE
     *
     * @param processType the value for gzsb_process.PROCESS_TYPE
     *
     * @mbg.generated
     */
    public void setProcessType(String processType) {
        this.processType = processType == null ? null : processType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_process.APPLY_TIME
     *
     * @return the value of gzsb_process.APPLY_TIME
     *
     * @mbg.generated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_process.APPLY_TIME
     *
     * @param applyTime the value for gzsb_process.APPLY_TIME
     *
     * @mbg.generated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }
}