package com.gzsb.root.gzsbroot.dao.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.List;
@Data
public class RolePermission   {
    /*
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_ROLE_PERMISSION.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_ROLE_PERMISSION.PERMISSION_CODE
     *
     * @mbg.generated
     */
    private String permissionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GZSB_ROLE_PERMISSION.ROLE_CODE
     *
     * @mbg.generated
     */
    private String roleCode;

    private List<String> permissionCodes;


}