package com.gzsb.root.gzsbroot.dao.entity;

import java.io.Serializable;

public class Status  {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_status.PLAN_STATUS_CODE
     *
     * @mbg.generated
     */
    private String planStatusCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_status.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_status.PLAN_STATUS_CODE
     *
     * @return the value of gzsb_status.PLAN_STATUS_CODE
     *
     * @mbg.generated
     */
    public String getPlanStatusCode() {
        return planStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_status.PLAN_STATUS_CODE
     *
     * @param planStatusCode the value for gzsb_status.PLAN_STATUS_CODE
     *
     * @mbg.generated
     */
    public void setPlanStatusCode(String planStatusCode) {
        this.planStatusCode = planStatusCode == null ? null : planStatusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_status.DESCRIPTION
     *
     * @return the value of gzsb_status.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_status.DESCRIPTION
     *
     * @param description the value for gzsb_status.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}