package com.gzsb.root.gzsbroot.dao.entity;

import java.io.Serializable;

public class Type  {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_type.TYPE_CODE
     *
     * @mbg.generated
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_type.FATHER_CODE
     *
     * @mbg.generated
     */
    private String fatherCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzsb_type.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_type.TYPE_CODE
     *
     * @return the value of gzsb_type.TYPE_CODE
     *
     * @mbg.generated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_type.TYPE_CODE
     *
     * @param typeCode the value for gzsb_type.TYPE_CODE
     *
     * @mbg.generated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_type.FATHER_CODE
     *
     * @return the value of gzsb_type.FATHER_CODE
     *
     * @mbg.generated
     */
    public String getFatherCode() {
        return fatherCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_type.FATHER_CODE
     *
     * @param fatherCode the value for gzsb_type.FATHER_CODE
     *
     * @mbg.generated
     */
    public void setFatherCode(String fatherCode) {
        this.fatherCode = fatherCode == null ? null : fatherCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzsb_type.DESCRIPTION
     *
     * @return the value of gzsb_type.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzsb_type.DESCRIPTION
     *
     * @param description the value for gzsb_type.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}